theme: jekyll-theme-minimal
title: Shreya Prasad (shreyateeza)
author: shreyateeza
email: shreyateeza@gmail.com
description: > # this means to ignore newlines until "twitter_username:"
  Shreya Prasad's Portfolio and Blog

# social links
twitter_username: shreyateeza
github_username:  shreyateeza
# rss: rss
# dribbble_username: jekyll
# facebook_username: shreyateeza
# flickr_username: jekyll
instagram_username: shreyateeza
linkedin_username: shreyateeza
# pinterest_username: jekyll
# youtube_username: shreyateeza
# youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
# youtube_channel_name: CloudCannon
# telegram_username: jekyll
# googleplus_username: +jekyll
# microdotblog_username: jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
 - about.md
 - experience.md
 - projects.md
 - certifications.md
 - achievements.md
 - contact.md


plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-remote-theme 
